version: 0.2

phases:
  install:
    # Definir el runtime adecuado
  pre_build:
    commands:
      - echo Instalar las dependencias de Python
  build:
    commands:
      - echo Ejecutar comando de pruebas pytest
